export const RSC_RUE_RUNTIME_ENTRIES = Object.freeze([] as string[])

export const RSC_RUE_CLIENT_OPTIMIZE_INCLUDE = RSC_RUE_RUNTIME_ENTRIES

export const RSC_RUE_NODE_EXTERNALS = RSC_RUE_RUNTIME_ENTRIES

export const RSC_RUE_OPTIMIZE_DEPS_EXCLUDE = RSC_RUE_RUNTIME_ENTRIES

export const RSC_RUE_DEDUPE = RSC_RUE_RUNTIME_ENTRIES

export const RSC_RUE_SSR_EXTERNAL_ENTRIES = RSC_RUE_RUNTIME_ENTRIES

export const RSC_RUE_SERVER_DOM_CLIENT_EDGE = ''
