export { cacheForRequest } from './shims/cache-for-request.js'
export {
  type ExecutionContextLike,
  getRequestExecutionContext,
  runWithExecutionContext,
} from './shims/request-context.js'
export {
  type ActionRevalidationKind,
  type CacheControlMetadata,
  type CacheHandler,
  type CacheHandlerContext,
  type CacheHandlerValue,
  type CacheLifeConfig,
  type CacheState,
  type CachedAppPageValue,
  type CachedFetchValue,
  type CachedImageValue,
  type CachedPagesValue,
  type CachedRedirectValue,
  type CachedRouteValue,
  type IncrementalCacheValue,
  MemoryCacheHandler,
  NoOpCacheHandler,
  type UnstableCacheRevalidationMode,
  _consumeRequestScopedCacheLife,
  _initRequestScopedCacheState,
  _peekRequestScopedCacheLife,
  _registerCacheContextAccessor,
  _runWithCacheState,
  _setRequestScopedCacheLife,
  cacheLife,
  cacheLifeProfiles,
  cacheTag,
  getAndClearActionRevalidationKind,
  getCacheHandler,
  io,
  isInsideUnstableCacheScope,
  noStore,
  noStore as unstable_noStore,
  refresh,
  revalidatePath,
  revalidateTag,
  setCacheHandler,
  unstable_cache,
  unstable_cacheLife,
  unstable_cacheTag,
  unstable_io,
  updateTag,
} from './shims/cache.js'
