/**
 * Type shim for the virtual RSC entry module generated by text at build time.
 *
 * The default export is the request handler. Named exports `__assetPrefix`
 * and `__basePath` are inlined string literals from text.config — they are
 * consumed by `server/app-router-entry.ts` for asset-shaped 404 detection
 * without invoking the handler. See `entries/app-rsc-entry.ts` for the
 * generator that emits these.
 */
declare module 'virtual:text-rsc-entry' {
  const rscHandler: (
    request: Request,
    ctx?: unknown,
  ) => Promise<Response | null | undefined | string>
  export default rscHandler
  export const __assetPrefix: string
  export const __basePath: string
}
