// This file is generated by text. Do not edit.
import type { Renderable } from '@rue-js/rue'

declare global {
  type PageProps<Route extends TextRouteTypes.PageRoute = TextRouteTypes.PageRoute> = {
    params: Promise<TextRouteTypes.ParamMap[Route]>
    searchParams: Promise<Record<string, string | string[] | undefined>>
  }

  type LayoutProps<Route extends TextRouteTypes.LayoutRoute> = {
    params: Promise<TextRouteTypes.ParamMap[Route]>
    children: Renderable
  } & {
    [K in TextRouteTypes.LayoutSlotMap[Route]]: Renderable
  }

  type RouteContext<
    Route extends TextRouteTypes.RouteHandlerRoute = TextRouteTypes.RouteHandlerRoute,
  > = {
    params: Promise<TextRouteTypes.ParamMap[Route]>
  }
}

declare namespace TextRouteTypes {
  type PageRoute = '/' | '/call-not-found'
  type LayoutRoute = '/'
  type RouteHandlerRoute = never
  type AppRoute = '/' | '/call-not-found'

  interface ParamMap {
    '/': {}
    '/call-not-found': {}
  }

  interface LayoutSlotMap {
    '/': never
  }
}

export {}
