import { createRequire } from 'node:module'

import { wrapCreateRue } from './runtime-entry-wrap.js'
import { installSharedBridge } from './vapor-bridge.js'
// Node 入口复用 reactive.node.js 的 JS 包装 API，保持 SSR/测试环境和浏览器入口一致。
import {
  computed,
  createComputed,
  createReactive,
  effectScope,
  getCurrentScope,
  isRef,
  isReadonly,
  nextTick,
  onRenderTracked,
  onWatcherCleanup,
  propsReactive,
  reactive,
  readonly,
  shallowRef,
  shallowReadonly,
  toRef,
  toRefs,
  triggerRef,
  watch,
  watchEffect,
  watchPostEffect,
  watchSyncEffect,
} from './reactive.node.js'

const require = createRequire(import.meta.url)
const runtimeVapor = require('./pkg-node/rue_runtime_vapor.js')
installSharedBridge(runtimeVapor)
const createRue = wrapCreateRue(runtimeVapor.createRue)

const {
  EffectHandle,
  SignalHandle,
  WasmRue,
  batch,
  createEffect,
  createRef,
  createResource,
  createCustomRef,
  createSignal,
  customRef,
  getCurrentInstance,
  isProxy,
  isReactive,
  onCleanup,
  onScopeDispose,
  ref,
  setCurrentInstance,
  setReactiveScheduling,
  shallowReactive,
  signal,
  toRaw,
  toValue,
  unref,
  untrack,
  useCallback,
  useEffect,
  useMemo,
  useRef,
  useSetup,
  useSignal,
  useState,
  vaporWithHookId,
  watchDeepSignal,
  watchFn,
  watchPath,
  watchSignal,
  withHookSlot,
} = runtimeVapor

export default {
  ...runtimeVapor,
  computed,
  createComputed,
  createReactive,
  createRue,
  effectScope,
  getCurrentScope,
  isRef,
  isReadonly,
  nextTick,
  onRenderTracked,
  propsReactive,
  reactive,
  readonly,
  shallowRef,
  shallowReadonly,
  toRef,
  toRefs,
  triggerRef,
  watch,
  watchEffect,
  watchPostEffect,
  watchSyncEffect,
}

export {
  EffectHandle,
  SignalHandle,
  WasmRue,
  batch,
  computed,
  createComputed,
  createEffect,
  createReactive,
  createRef,
  createResource,
  createCustomRef,
  createRue,
  createSignal,
  customRef,
  effectScope,
  getCurrentScope,
  getCurrentInstance,
  isRef,
  isReadonly,
  isProxy,
  isReactive,
  nextTick,
  onCleanup,
  onWatcherCleanup,
  onRenderTracked,
  onScopeDispose,
  propsReactive,
  reactive,
  readonly,
  ref,
  setCurrentInstance,
  setReactiveScheduling,
  shallowRef,
  toRef,
  toRefs,
  triggerRef,
  watch,
  watchEffect,
  watchPostEffect,
  watchSyncEffect,
  shallowReactive,
  shallowReadonly,
  signal,
  toRaw,
  toValue,
  unref,
  untrack,
  useCallback,
  useEffect,
  useMemo,
  useRef,
  useSetup,
  useSignal,
  useState,
  vaporWithHookId,
  watchDeepSignal,
  watchFn,
  watchPath,
  watchSignal,
  withHookSlot,
}
