import { createRue as createJsRue } from './js-runtime/create-rue.js'
import { wrapCreateRue } from './runtime-entry-wrap.js'
import { installSharedBridge } from './vapor-bridge.js'
// Node 入口复用 reactive.node.js 的 JS 包装 API，保持 SSR/测试环境和浏览器入口一致。
import {
  computed,
  createComputed,
  createReactive,
  createSignal,
  effectScope,
  getCurrentScope,
  isRef,
  isReadonly,
  nextTick,
  normalizeRenderTriggeredEvent,
  onRenderTracked,
  onWatcherCleanup,
  propsReactive,
  reactive,
  readonly,
  shallowRef,
  shallowReadonly,
  signal,
  toRef,
  toRefs,
  triggerRef,
  watch,
  watchEffect,
  watchPostEffect,
  watchSyncEffect,
} from './reactive.node.js'
import runtimeWithJsHooks from './reactive.node.js'

installSharedBridge(runtimeWithJsHooks)
const createJsRuntime = (adapter: unknown) => {
  if (typeof __TEST__ !== 'undefined' && __TEST__) {
    globalThis.__rue_runtime_vapor_backend_test_hook__?.({
      entry: 'node:full',
      hooks: 'js',
      kernel: 'pkg-node',
      runtime: 'js',
    })
  }
  return createJsRue(adapter, runtimeWithJsHooks)
}
const createRue = wrapCreateRue(createJsRuntime, normalizeRenderTriggeredEvent)

export type { RueRuntime } from './js-runtime/types.js'

const {
  EffectHandle,
  SignalHandle,
  batch,
  createEffect,
  createRef,
  createResource,
  createCustomRef,
  customRef,
  getCurrentInstance,
  isProxy,
  isReactive,
  onCleanup,
  onScopeDispose,
  ref,
  setCurrentInstance,
  setReactiveScheduling,
  shallowReactive,
  toRaw,
  toValue,
  unref,
  untrack,
  useCallback,
  useEffect,
  useMemo,
  useRef,
  useSetup,
  useSignal,
  useState,
  vaporWithHookId,
  watchDeepSignal,
  watchFn,
  watchPath,
  watchSignal,
  withHookSlot,
} = runtimeWithJsHooks

export default {
  ...runtimeWithJsHooks,
  computed,
  createComputed,
  createReactive,
  createSignal,
  createRue,
  effectScope,
  getCurrentScope,
  isRef,
  isReadonly,
  nextTick,
  onRenderTracked,
  propsReactive,
  reactive,
  readonly,
  shallowRef,
  shallowReadonly,
  signal,
  toRef,
  toRefs,
  triggerRef,
  watch,
  watchEffect,
  watchPostEffect,
  watchSyncEffect,
}

export {
  EffectHandle,
  SignalHandle,
  batch,
  computed,
  createComputed,
  createEffect,
  createReactive,
  createRef,
  createResource,
  createCustomRef,
  createRue,
  createSignal,
  customRef,
  effectScope,
  getCurrentScope,
  getCurrentInstance,
  isRef,
  isReadonly,
  isProxy,
  isReactive,
  nextTick,
  onCleanup,
  onWatcherCleanup,
  onRenderTracked,
  onScopeDispose,
  propsReactive,
  reactive,
  readonly,
  ref,
  setCurrentInstance,
  setReactiveScheduling,
  shallowRef,
  toRef,
  toRefs,
  triggerRef,
  watch,
  watchEffect,
  watchPostEffect,
  watchSyncEffect,
  shallowReactive,
  shallowReadonly,
  signal,
  toRaw,
  toValue,
  unref,
  untrack,
  useCallback,
  useEffect,
  useMemo,
  useRef,
  useSetup,
  useSignal,
  useState,
  vaporWithHookId,
  watchDeepSignal,
  watchFn,
  watchPath,
  watchSignal,
  withHookSlot,
}
