import * as runtimeVapor from './pkg/rue_runtime_vapor.js'

import { wrapCreateRue } from './runtime-entry-wrap.js'

const createRue = wrapCreateRue(runtimeVapor.createRue)

const {
  EffectHandle,
  SignalHandle,
  WasmRue,
  batch,
  computed,
  createComputed,
  createEffect,
  createReactive,
  createRef,
  createResource,
  createSignal,
  getCurrentInstance,
  isReactive,
  onCleanup,
  propsReactive,
  reactive,
  readonly,
  ref,
  setCurrentInstance,
  setReactiveScheduling,
  shallowReactive,
  shallowReadonly,
  signal,
  toRaw,
  toValue,
  unref,
  untrack,
  useCallback,
  useEffect,
  useMemo,
  useRef,
  useSetup,
  useSignal,
  useState,
  vaporWithHookId,
  watch,
  watchDeepSignal,
  watchEffect,
  watchFn,
  watchPath,
  watchSignal,
  withHookSlot,
} = runtimeVapor

export * from './pkg/rue_runtime_vapor.js'

export default {
  ...runtimeVapor,
  createRue,
}

export {
  EffectHandle,
  SignalHandle,
  WasmRue,
  batch,
  computed,
  createComputed,
  createEffect,
  createReactive,
  createRef,
  createResource,
  createRue,
  createSignal,
  getCurrentInstance,
  isReactive,
  onCleanup,
  propsReactive,
  reactive,
  readonly,
  ref,
  setCurrentInstance,
  setReactiveScheduling,
  shallowReactive,
  shallowReadonly,
  signal,
  toRaw,
  toValue,
  unref,
  untrack,
  useCallback,
  useEffect,
  useMemo,
  useRef,
  useSetup,
  useSignal,
  useState,
  vaporWithHookId,
  watch,
  watchDeepSignal,
  watchEffect,
  watchFn,
  watchPath,
  watchSignal,
  withHookSlot,
}
