import * as runtimeVapor from './pkg/rue_runtime_vapor.js'

import { wrapCreateRue } from './runtime-entry-wrap.js'
// JS 包装层补充响应式便捷 API 与调试 hooks，默认入口与 reactive 子入口保持同一实现。
import {
  computed,
  createComputed,
  createReactive,
  getCurrentScope,
  isRef,
  isReadonly,
  nextTick,
  onRenderTracked,
  onWatcherCleanup,
  propsReactive,
  reactive,
  readonly,
  shallowRef,
  shallowReadonly,
  toRef,
  toRefs,
  triggerRef,
  watchPostEffect,
} from './reactive.js'

const createRue = wrapCreateRue(runtimeVapor.createRue)

const {
  EffectHandle,
  SignalHandle,
  WasmRue,
  batch,
  createEffect,
  createRef,
  createResource,
  createSignal,
  getCurrentInstance,
  isProxy,
  isReactive,
  onCleanup,
  onScopeDispose,
  ref,
  setCurrentInstance,
  setReactiveScheduling,
  shallowReactive,
  signal,
  toRaw,
  toValue,
  unref,
  untrack,
  useCallback,
  useEffect,
  useMemo,
  useRef,
  useSetup,
  useSignal,
  useState,
  vaporWithHookId,
  watch,
  watchDeepSignal,
  watchEffect,
  watchFn,
  watchPath,
  watchSignal,
  withHookSlot,
} = runtimeVapor

export * from './pkg/rue_runtime_vapor.js'

export default {
  ...runtimeVapor,
  computed,
  createComputed,
  createReactive,
  createRue,
  getCurrentScope,
  isRef,
  isReadonly,
  nextTick,
  onRenderTracked,
  propsReactive,
  reactive,
  readonly,
  shallowRef,
  shallowReadonly,
  toRef,
  toRefs,
  triggerRef,
  watchPostEffect,
}

export {
  EffectHandle,
  SignalHandle,
  WasmRue,
  batch,
  computed,
  createComputed,
  createEffect,
  createReactive,
  createRef,
  createResource,
  createRue,
  createSignal,
  getCurrentScope,
  getCurrentInstance,
  isRef,
  isReadonly,
  isProxy,
  isReactive,
  nextTick,
  onCleanup,
  onWatcherCleanup,
  onRenderTracked,
  onScopeDispose,
  propsReactive,
  reactive,
  readonly,
  ref,
  setCurrentInstance,
  setReactiveScheduling,
  shallowRef,
  toRef,
  toRefs,
  triggerRef,
  watchPostEffect,
  shallowReactive,
  shallowReadonly,
  signal,
  toRaw,
  toValue,
  unref,
  untrack,
  useCallback,
  useEffect,
  useMemo,
  useRef,
  useSetup,
  useSignal,
  useState,
  vaporWithHookId,
  watch,
  watchDeepSignal,
  watchEffect,
  watchFn,
  watchPath,
  watchSignal,
  withHookSlot,
}
