import { createRuntimeEntry } from './runtime-entry.js'
import { createRue as createFullRue } from './js-runtime/create-rue.js'
// Node 入口复用 reactive.node.js 的 JS 包装 API，保持 SSR/测试环境和浏览器入口一致。
import {
  computed,
  createComputed,
  createReactive,
  createSignal,
  effectScope,
  getCurrentScope,
  isRef,
  isReadonly,
  nextTick,
  normalizeRenderTriggeredEvent,
  onRenderTracked,
  onWatcherCleanup,
  propsReactive,
  reactive,
  readonly,
  shallowRef,
  shallowReadonly,
  signal,
  toRef,
  toRefs,
  triggerRef,
  watch,
  watchEffect,
  watchPostEffect,
  watchSyncEffect,
} from './reactive.node.js'
import runtimeWithJsHooks from './reactive.node.js'

const createRue = createRuntimeEntry(runtimeWithJsHooks, createFullRue, {
  entry: 'node:full',
  kernel: 'typescript',
  normalizeRenderTriggeredEvent,
})

export type { RueRuntime } from './js-runtime/types.js'

const {
  EffectHandle,
  SignalHandle,
  batch,
  createEffect,
  createRef,
  createResource,
  createCustomRef,
  customRef,
  getCurrentInstance,
  isProxy,
  isReactive,
  onCleanup,
  onScopeDispose,
  ref,
  setCurrentInstance,
  setReactiveScheduling,
  shallowReactive,
  toRaw,
  toValue,
  unref,
  untrack,
  useEffect,
  useRef,
  useSetup,
  useState,
  vaporWithHookId,
  watchDeepSignal,
  watchFn,
  watchPath,
  watchSignal,
  withHookSlot,
} = runtimeWithJsHooks

export default {
  ...runtimeWithJsHooks,
  computed,
  createComputed,
  createReactive,
  createSignal,
  createRue,
  effectScope,
  getCurrentScope,
  isRef,
  isReadonly,
  nextTick,
  onRenderTracked,
  propsReactive,
  reactive,
  readonly,
  shallowRef,
  shallowReadonly,
  signal,
  toRef,
  toRefs,
  triggerRef,
  watch,
  watchEffect,
  watchPostEffect,
  watchSyncEffect,
}

export {
  EffectHandle,
  SignalHandle,
  batch,
  computed,
  createComputed,
  createEffect,
  createReactive,
  createRef,
  createResource,
  createCustomRef,
  createRue,
  createSignal,
  customRef,
  effectScope,
  getCurrentScope,
  getCurrentInstance,
  isRef,
  isReadonly,
  isProxy,
  isReactive,
  nextTick,
  onCleanup,
  onWatcherCleanup,
  onRenderTracked,
  onScopeDispose,
  propsReactive,
  reactive,
  readonly,
  ref,
  setCurrentInstance,
  setReactiveScheduling,
  shallowRef,
  toRef,
  toRefs,
  triggerRef,
  watch,
  watchEffect,
  watchPostEffect,
  watchSyncEffect,
  shallowReactive,
  shallowReadonly,
  signal,
  toRaw,
  toValue,
  unref,
  untrack,
  useEffect,
  useRef,
  useSetup,
  useState,
  vaporWithHookId,
  watchDeepSignal,
  watchFn,
  watchPath,
  watchSignal,
  withHookSlot,
}
