import { createRuntimeEntry } from './runtime-entry.js'
import { createRue as createFullRue } from './js-runtime/create-rue.js'
// JS 包装层补充响应式便捷 API 与调试 hooks，默认入口与 reactive 子入口保持同一实现。
import {
  computed,
  createComputed,
  createReactive,
  createSignal,
  effectScope,
  getCurrentScope,
  isRef,
  isReadonly,
  nextTick,
  normalizeRenderTriggeredEvent,
  onRenderTracked,
  onWatcherCleanup,
  propsReactive,
  reactive,
  readonly,
  shallowRef,
  shallowReadonly,
  signal,
  toRef,
  toRefs,
  triggerRef,
  watch,
  watchEffect,
  watchPostEffect,
  watchSyncEffect,
} from './reactive.js'
import runtimeWithJsHooks from './reactive.js'

const createRue = createRuntimeEntry(runtimeWithJsHooks, createFullRue, {
  entry: 'browser:full',
  kernel: 'typescript',
  normalizeRenderTriggeredEvent,
})

const {
  EffectHandle,
  SignalHandle,
  batch,
  createEffect,
  createRef,
  createResource,
  createCustomRef,
  customRef,
  getCurrentInstance,
  isProxy,
  isReactive,
  onCleanup,
  onScopeDispose,
  ref,
  setCurrentInstance,
  setReactiveScheduling,
  shallowReactive,
  toRaw,
  toValue,
  unref,
  untrack,
  useEffect,
  useRef,
  useSetup,
  useState,
  vaporWithHookId,
  watchDeepSignal,
  watchFn,
  watchPath,
  watchSignal,
  withHookSlot,
} = runtimeWithJsHooks

export type { RueRuntime } from './js-runtime/types.js'
export type SignalHandle<T> = import('./js-reactive/types.js').SignalHandle<T>
export type {
  ComputedHandle,
  Dispatch,
  DebuggerEvent,
  DebuggerHook,
  EffectScope,
  EqualityOptions as UseStateOptions,
  ReadonlyRefLike as GetterRef,
  RefLike as ObjectRef,
  RefSlot as HookRef,
  SetStateAction,
  StateSetter as ReactiveStateSetter,
  StateSetter as RefStateSetter,
  WatchCallback,
  WatchEffectOptions,
  WatchFlush,
  WatchOptions,
  WatchSource,
} from './js-reactive/types.js'

export default {
  ...runtimeWithJsHooks,
  computed,
  createComputed,
  createReactive,
  createSignal,
  createRue,
  effectScope,
  getCurrentScope,
  isRef,
  isReadonly,
  nextTick,
  onRenderTracked,
  propsReactive,
  reactive,
  readonly,
  shallowRef,
  shallowReadonly,
  signal,
  toRef,
  toRefs,
  triggerRef,
  watch,
  watchEffect,
  watchPostEffect,
  watchSyncEffect,
}

export {
  EffectHandle,
  SignalHandle,
  batch,
  computed,
  createComputed,
  createEffect,
  createReactive,
  createRef,
  createResource,
  createCustomRef,
  createRue,
  createSignal,
  customRef,
  effectScope,
  getCurrentScope,
  getCurrentInstance,
  isRef,
  isReadonly,
  isProxy,
  isReactive,
  nextTick,
  onCleanup,
  onWatcherCleanup,
  onRenderTracked,
  onScopeDispose,
  propsReactive,
  reactive,
  readonly,
  ref,
  setCurrentInstance,
  setReactiveScheduling,
  shallowRef,
  toRef,
  toRefs,
  triggerRef,
  watch,
  watchEffect,
  watchPostEffect,
  watchSyncEffect,
  shallowReactive,
  shallowReadonly,
  signal,
  toRaw,
  toValue,
  unref,
  untrack,
  useEffect,
  useRef,
  useSetup,
  useState,
  vaporWithHookId,
  watchDeepSignal,
  watchFn,
  watchPath,
  watchSignal,
  withHookSlot,
}
