/** Public built-in component facade. */
export { Slot, type SlotBag, type SlotProps, type SlotValue } from '../components/Slot'
export { Component, type DynamicComponentProps } from '../components/Component'
export { KeepAlive } from '../components/KeepAlive'
export type { KeepAliveMatchPattern, KeepAliveProps } from '../components/KeepAlive'
export { Suspense } from '../components/Suspense'
export type { SuspenseProps } from '../components/Suspense'
export { Template, type TemplateProps } from '../components/Template'
export { Teleport, type TeleportProps } from '../components/Teleport'
export { createTransitionRunner, type BaseTransitionProps } from '../components/BaseTransition'
export * as TransitionUtils from '../components/transitionUtils'
export { Transition } from '../components/Transition'
export type { TransitionMode, TransitionProps } from '../components/Transition'
export { TransitionGroup } from '../components/TransitionGroup'
export type { TransitionGroupProps } from '../components/TransitionGroup'
